### ISSUE TITLE
Uncaught TypeError: Cannot read property 'top' of undefined

### ISSUE THREAD

**Issue by reminyborg** [fundon/atom-minimap#216] opened 2015-01-13 08:45 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.168.0
**System**: Mac OS X 10.10.1
**Thrown From**: [minimap](https://github.com/fundon/atom-minimap) package, v3.3.4

### Stack Trace

Uncaught TypeError: Cannot read property 'top' of undefined

```
At /Users/remi/.atom/packages/minimap/lib/minimap-view.coffee:353

TypeError: Cannot read property 'top' of undefined
  at MinimapView.module.exports.MinimapView.updateScrollY (/Users/remi/.atom/packages/minimap/lib/minimap-view.coffee:353:64)
  at MinimapView.updateScrollY (/Users/remi/.atom/packages/minimap/lib/minimap-view.coffee:1:1)
  at MinimapView.module.exports.MinimapView.updateScroll (/Users/remi/.atom/packages/minimap/lib/minimap-view.coffee:368:6)
  at MinimapView.updateScroll (/Users/remi/.atom/packages/minimap/lib/minimap-view.coffee:1:1)
  at /Users/remi/.atom/packages/minimap/lib/minimap-view.coffee:268:8

```

### Commands

```
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

/cc @atom/core

**Comment by abe33** [comment] 2015-01-13 08:56
Please at least take the time to look for existing closed issues, it's at least the tenth duplicate of this issue, which is caused by a lack of update of the package on your end.

**Closed by abe33** 2015-01-13 08:56 UTC

**Comment by reminyborg** [comment] 2015-01-13 08:58
Sorry about this. Atoms automatic issue reporting makes it to easy to create an issue without checking for existing issues.

**Comment by abe33** [comment] 2015-01-13 09:12
What's puzzle me is why that many people doesn't get notified of the packages update.
