### ISSUE TITLE
Uncaught TypeError: Cannot read property 'tokens' of undefined

### ISSUE THREAD

**Issue by loque** [fundon/atom-minimap#209] opened 2015-01-08 17:08 UTC
[Enter steps to reproduce below:]

1. click on the minimap
2. atom freezes

**Atom Version**: 0.166.0
**System**: Unknown Windows Version
**Thrown From**: [minimap](https://github.com/fundon/atom-minimap) package, v3.5.4

### Stack Trace

Uncaught TypeError: Cannot read property 'tokens' of undefined

```
At c:\Users\Lucas\AppData\Local\atom\app-0.166.0\resources\app\src\display-buffer.js:958

TypeError: Cannot read property 'tokens' of undefined
  at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForPixelPosition (c:\Users\Lucas\AppData\Local\atom\app-0.166.0\resources\app\src\display-buffer.js:958:50)
  at MinimapView.module.exports.MinimapView.onMouseDown (c:\Users\Lucas\.atom\packages\minimap\lib\minimap-view.coffee:500:27)
  at space-pen-div.<anonymous> (c:\Users\Lucas\.atom\packages\minimap\lib\minimap-view.coffee:1:1)

```

### Commands

```
     -3:39.0 core:save (atom-text-editor.editor)
     -3:12.3 editor:move-to-first-character-of-line (atom-text-editor.editor)
     -3:11.4 core:save (atom-text-editor.editor)
     -2:37.9 tab-history:previous (atom-text-editor.editor)
     -2:33.7 core:save (atom-text-editor.editor)
     -1:42.7 color-picker:open (atom-text-editor.editor)
     -1:40.8 editor:consolidate-selections (atom-text-editor.editor)
     -1:40.8 core:cancel (atom-text-editor.editor)
     -1:08.1 tab-history:previous (atom-text-editor.editor)
     -1:03.4 core:save (atom-text-editor.editor)
     -0:09.3 editor:duplicate-lines (atom-text-editor.editor)
     -0:08.1 core:paste (atom-text-editor.editor)
     -0:07.2 core:save (atom-text-editor.editor)
     -0:01.1 core:move-down (atom-text-editor.editor)
     -0:00.8 editor:move-to-first-character-of-line (atom-text-editor.editor)
     -0:00.0 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "symbols-view"
    ],
    "autoHideMenuBar": true
  },
  "minimap": {
    "plugins": {
      "highlight-selected": true,
      "find-and-replace": true
    }
  }
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.13.0
color-picker, v1.2.6
highlight-selected, v0.7.0
html-helper, v0.2.3
linter, v0.9.1
linter-csslint, v0.0.11
linter-htmlhint, v0.0.8
linter-js-yaml, v0.1.3
linter-jshint, v0.1.0
linter-php, v0.0.11
linter-scss-lint, v0.0.11
minimap, v3.5.4
minimap-find-and-replace, v3.1.0
minimap-highlight-selected, v3.1.0
php-twig, v3.0.0
project-manager, v1.14.1
react, v0.7.8
Stylus, v0.4.0
tab-history, v0.4.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by abe33** [comment] 2015-01-08 18:55
Likeky a duplicate of #204, can you confirm?

**Comment by loque** [comment] 2015-01-08 19:01
Yes, it is. Now Atom has uninstalled itself after crashing.. so it might be something else.

**Comment by abe33** [comment] 2015-01-08 22:40
Oh! Seems pretty serious, Atom was uninstalled by a crash? You should report this on atom/atom.

**Comment by djlosch** [comment] 2015-01-08 23:32
confirming this also happens on the mac client, save version numbers

**Comment by abe33** [comment] 2015-01-09 00:18
The thing is the error's stack doesn't match the source code of the specified version (there's no longer a call to `screenPositionForPixelPosition` in 3.5.4), which means that the error might have been triggered after an update of the minimap package and before a restart of atom, when the previous code may have been cached and not reloaded properly by Atom after the update. The 3.5.4 update specifically targeted this error and so I don't see any simple for me to fix that. The error is pretty much due to Atom handling of updates, I'll check whether an issue have been filled for this scenario in the core or not.

**Comment by abe33** [comment] 2015-02-12 08:54
No more informations? I'm closing it for now.

**Closed by abe33** 2015-02-12 08:54 UTC

**Comment by SergejJurecko** [comment] 2015-06-10 05:51
In latest atom which supports large files. Opening sqlite3.c will cause this exception once it reaches the bottom:

/Users/sergej/.atom/packages/minimap/lib/mixins/canvas-drawer.coffee:175
Hide Stack Trace
TypeError: Cannot read property 'tokens' of undefined
  at atom-text-editor-minimap.module.exports.CanvasDrawer.drawLines (/Users/sergej/.atom/packages/minimap/lib/mixins/canvas-drawer.coffee:175:7)
  at atom-text-editor-minimap.module.exports.CanvasDrawer.updateCanvas (/Users/sergej/.atom/packages/minimap/lib/mixins/canvas-drawer.coffee:34:8)
  at atom-text-editor-minimap.MinimapElement.update (/Users/sergej/.atom/packages/minimap/lib/minimap-element.coffee:364:6)
  at /Users/sergej/.atom/packages/minimap/lib/minimap-element.coffee:312:8

**Comment by sadovnychyi** [comment] 2015-06-10 11:07
:+1: same for me @SergejJurecko

**Comment by pwagland** [comment] 2015-06-10 11:18
I get the same issue on any file greater than 2MB. Any file less than 2MB does not have the problem. It would appear that the module is relying on something which is no longer being loaded for large files. This only happens, for me, when scrolling to the end of the file

**Comment by abe33** [comment] 2015-06-10 21:00
@SergejJurecko, @sadovnychyi, @pwagland Can one of you open a new issue with the stack trace you get?
For me it's unlikely to be the same issue (not with almost 6 months inbetween).
