### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPropertyValue' of null

### ISSUE THREAD

**Issue by nanorepublica** [fundon/atom-minimap#189] opened 2014-12-31 08:33 UTC
[Enter steps to reproduce below:]

1. Just opening atom produces this, happens each time the editor is started

**Atom Version**: 0.165.0
**System**: Mac OS X 10.10.1
**Thrown From**: [minimap](https://github.com/fundon/atom-minimap) package, v3.4.9

### Stack Trace

Uncaught TypeError: Cannot read property 'getPropertyValue' of null

```
At /Users/amiller/.atom/packages/minimap/lib/minimap-view.coffee:198

TypeError: Cannot read property 'getPropertyValue' of null
  at MinimapView.module.exports.MinimapView.getEditorLineHeight (/Users/amiller/.atom/packages/minimap/lib/minimap-view.coffee:198:87)
  at MinimapView.module.exports.MinimapView.computeScale (/Users/amiller/.atom/packages/minimap/lib/minimap-view.coffee:192:27)
  at /Users/amiller/.atom/packages/minimap/lib/minimap-view.coffee:170:8
  at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:568:7)
  at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app/src/config.js:134:21)
  at MinimapView.module.exports.MinimapView.initialize (/Users/amiller/.atom/packages/minimap/lib/minimap-view.coffee:169:36)
  at MinimapView.View (/Users/amiller/.atom/packages/linter/node_modules/space-pen/lib/space-pen.js:178:25)
  at new MinimapView (/Users/amiller/.atom/packages/minimap/lib/minimap-view.coffee:86:5)
  at Minimap.module.exports.ViewManagement.onEditorAdded (/Users/amiller/.atom/packages/minimap/lib/mixins/view-management.coffee:105:16)
  at /Users/amiller/.atom/packages/minimap/lib/mixins/view-management.coffee:85:37

```

### Commands

```
```

### Config

```
{
  "core": {
    "disabledPackages": [
      "travis-ci-status"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "projectHome": "/Users/amiller"
  },
  "minimap": {
    "plugins": {
      "find-and-replace": true,
      "selection": true,
      "git-diff": true
    }
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-paths, v0.9.1
autocomplete-plus, v1.0.0
color-picker, v1.2.6
command-logger, v0.20.0
editor-stats, v0.16.0
git-log, v0.2.0
git-tab-status, v1.3.0
inline-autocomplete, v0.3.3
linter, v0.9.0
minimap, v3.4.9
minimap-color-highlight, v3.0.3
minimap-find-and-replace, v3.0.4
minimap-git-diff, v3.0.11
minimap-highlight-selected, v3.0.0
minimap-selection, v3.0.1
monokai, v0.9.0
pretty-json, v0.3.1
project-colorize, v0.1.0
project-manager, v1.14.1
project-ring, v0.18.2
recent-projects, v0.2.6
script, v2.15.1
set-syntax, v0.1.0
update-packages, v0.1.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by 190N** [comment] 2015-01-02 17:07
Happens for me on Ubuntu 14.10.
Also on Atom 0.165.

**Comment by abe33** [comment] 2015-01-02 23:09
Thanks for the report, it was already reported in #173. I haven't a solution yet, and I'll need people to try things on their machine because I can't reproduce this issue.

Closing it to keep the discussion in one place.

**Closed by abe33** 2015-01-02 23:09 UTC
